"""
CAP3D View - 3D Visualization for CAP3D Files

A comprehensive Python package for visualizing 3D geometry from CAP3D files
generated by the RWCap tool for capacitance calculations.

Features:
- Interactive 3D visualization with Plotly
- Legacy matplotlib support  
- Block construction animation
- Support for large file parsing
"""

__version__ = "2.0.0"
__author__ = "CAP3D View Contributors"

# Core parsing functions
from .cap3d_matplotlib import parse_cap3d, create_block_vertices

# Visualization modules
from .cap3d_plotly import draw_components_plotly, create_interactive_dashboard, show_visualization_menu
from .cap3d_matplotlib import draw_components

__all__ = [
    # Core functions
    'parse_cap3d',
    'create_block_vertices',
    
    # Interactive visualization (recommended)
    'draw_components_plotly',
    'create_interactive_dashboard', 
    'show_visualization_menu',
    
    # Legacy visualization
    'draw_components',
] 