name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'cap3d_viz/**'
      - 'docs/**'
      - '*.md'
  pull_request:
    branches: [ main ]
    paths:
      - 'cap3d_viz/**'
      - 'docs/**'
      - '*.md'
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints myst-parser
        pip install -e .
    
    - name: Create docs directory structure
      run: |
        mkdir -p docs_build/source
        mkdir -p docs_build/source/_static
        mkdir -p docs_build/source/_templates
    
    - name: Generate API documentation
      run: |
        sphinx-apidoc -o docs_build/source cap3d_viz
    
    - name: Create Sphinx configuration
      run: |
        cat > docs_build/source/conf.py << 'EOF'
        import os
        import sys
        sys.path.insert(0, os.path.abspath('../../'))
        
        project = 'CAP3D-Viz'
        copyright = '2025, Ahmed Ali'
        author = 'Ahmed Ali'
        
        extensions = [
            'sphinx.ext.autodoc',
            'sphinx.ext.viewcode',
            'sphinx.ext.napoleon',
            'sphinx_rtd_theme',
            'myst_parser',
        ]
        
        templates_path = ['_templates']
        exclude_patterns = []
        
        html_theme = 'sphinx_rtd_theme'
        html_static_path = ['_static']
        
        autodoc_default_options = {
            'members': True,
            'member-order': 'bysource',
            'special-members': '__init__',
            'undoc-members': True,
            'exclude-members': '__weakref__'
        }
        EOF
    
    - name: Create main documentation file
      run: |
        cat > docs_build/source/index.rst << 'EOF'
        CAP3D-Viz Documentation
        =======================
        
        CAP3D-Viz is a high-performance Python package for parsing and visualizing 3D geometry 
        from CAP3D files generated by capacitance solvers.
        
        .. toctree::
           :maxdepth: 2
           :caption: Contents:
        
           installation
           quickstart
           api
           performance
           examples
        
        Features
        --------
        
        * **State-Machine Parser**: 70-80% reduction in condition checking
        * **Memory Efficient**: Handles 10,000+ blocks with <8MB memory usage  
        * **High Performance**: Parse speed of 9,882+ blocks/second
        * **Interactive 3D Visualization**: Real-time filtering and exploration
        * **Batched Rendering**: Smooth visualization of 50k+ blocks
        * **Professional IC Features**: Industry-standard layer colors
        
        Installation
        ------------
        
        Install from PyPI:
        
        .. code-block:: bash
        
           pip install cap3d-viz
        
        Quick Start
        -----------
        
        .. code-block:: python
        
           from cap3d_viz import load_and_visualize
           
           # Load and visualize a CAP3D file
           fig = load_and_visualize("your_file.cap3d")
           fig.show()
        
        Indices and tables
        ==================
        
        * :ref:`genindex`
        * :ref:`modindex`
        * :ref:`search`
        EOF
    
    - name: Create installation guide
      run: |
        cp docs/installation.md docs_build/source/installation.md
        cp docs/performance.md docs_build/source/performance.md
    
    - name: Create API documentation
      run: |
        cat > docs_build/source/api.rst << 'EOF'
        API Reference
        =============
        
        .. automodule:: cap3d_viz
           :members:
        
        Data Models
        -----------
        
        .. automodule:: cap3d_viz.data_models
           :members:
        
        Parser
        ------
        
        .. automodule:: cap3d_viz.parser
           :members:
        
        Visualizer
        ----------
        
        .. automodule:: cap3d_viz.visualizer
           :members:
        
        Utilities
        ---------
        
        .. automodule:: cap3d_viz.utils
           :members:
        EOF
    
    - name: Build documentation
      run: |
        cd docs_build
        sphinx-build -b html source build
    
    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs_build/build/
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs_build/build
